language: node_js
node_js:
  - '10'
cache: npm
branches:
  only:
    - pages
before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli
install:
  - cd hexo
  - npm install
before_script:
  - pwd
  - rm -rf ./source/_posts ./source/images
  - mkdir -p ./source/_posts/
  - mkdir -p ./source/images/
  - pwd
  - cp -r ../docs/ ./source/_posts/
  - cp -r ../images/ ./source/images/
script:
  - hexo clean
  - hexo generate
after_script:
  - cd public
  - git init
  - git config user.name "ruesin"
  - git config user.email "ruesin@gmail.com"
  - git remote add origin https://github.com/ruesin/notes.git
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GIT_TOKEN}@github.com/ruesin/notes.git" master:gh_pages
  # - git push --force --quiet "https://${GIT_TOKEN}@github.com/ruesin/ruesin.github.io.git" master:master